name: harry_potter_app
description: Una aplicación de Harry Potter que utiliza patrón MVC y consume una API pública.

# La siguiente línea evita que el paquete sea publicado accidentalmente en pub.dev
publish_to: 'none' 

# Versión y número de build - importante para despliegue
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Paquetes externos
  http: ^1.1.0           # Para realizar peticiones HTTP a la API
  provider: ^6.0.5       # Para la gestión del estado
  cached_network_image: ^3.3.0  # Para cargar y cachear imágenes de internet
  google_fonts: ^5.1.0   # Para utilizar fuentes de Google
  flutter_svg: ^2.0.7 
  
  # Iconos de Cupertino
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Herramientas de análisis de código
  flutter_lints: ^2.0.3

flutter:
  # El siguiente bloque asegura que el material Icons esté incluido
  uses-material-design: true
  assets:
    - assets/
    - assets/images/Harry_Potter_wordmark.svg
    - assets/images/gryffindor.png
    - assets/images/hufflepuff.png
    - assets/images/ravenclaw.png
    - assets/images/slytherin.png
